<?php $this->headScript()->appendFile($this->baseUrl().'/resources/js/jcrop/js/jquery.Jcrop.min.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/resources/js/jcrop/css/jquery.Jcrop.css');
?>
<?php $this->headScript()->captureStart(); ?>
	$(function(){
		var sizeX = <?php echo $this->imgWidth;?>;
		var sizeY = <?php echo $this->imgHeight;?>;
		var ratio = sizeX / sizeY;
		$('#cropbox').Jcrop({
			onChange: showCoords,
			onSelect: showCoords,
			setSelect: [0,0,sizeX,sizeY],
			aspectRatio: ratio,
			boxWidth: 800, 
			boxHeight: 500,
			bgOpacity:   .4
		});
 
		function showCoords(c)
		{
			$('#x').val(c.x);
			$('#y').val(c.y);
			$('#w').val(c.w);
			$('#h').val(c.h);
		};
	});
<?php echo $this->headScript()->captureEnd(); ?>

<style>
.ProfileImageCenter {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}
</style>

<div class="box">
<div class="box-body">
<div class="ProfileImageCenter">
<img  src="<?php echo $this->baseUrl()."/".$this->fileOriginalPath; ?>" id="cropbox" alt="cropbox" />
</div>
<?php echo $this->form;?>
</div>
</div>