<?php

# we are here to display profile owner's image
#of course you can do the necessary styling.
# haha I can already hear someone say. Do it. Let us do it
# img-thumbnail
# Alrright we are done. Mission accomplished.
# Please Like, Dislike, and comment to create some engagement so that the video can be recommended to others
# Cheers. Until next time...
echo '<img src="'.$this->basePath('images' . DS . 'pictures' . DS . $this->data->getPhoto()).'" class="img-thumbnail" alt="profile picture">';