
  <?php 
   		echo $this->headLink() ->prependStylesheet($this->baseUrl().'/resources/jQueryFileUploadmaster/css/jquery.fileupload-ui.css')
   		 ;
   ?>

<!-- CSS adjustments for browsers with JavaScript disabled -->
<noscript><?php 
   		echo $this->headLink()->prependStylesheet($this->baseUrl().'/resources/jQueryFileUploadmaster/css/jquery.fileupload-ui.css');
   ?></noscript>
<?php if($this->typetof!="grand"):?>
<h2>Image de profile</h2>
		<div align="center">
			<img src="<?php echo $this->baseUrl(); ?>/resources/images/admin/Penguins.jpg" style="float: left; margin-right: 10px;" id="thumbnail" alt="Create Thumbnail" />
			<div style="border:1px #e5e5e5 solid; float:left; position:relative; overflow:hidden; width:<?php echo $thumb_width;?>px; height:<?php echo $thumb_height;?>px;">
				<img src="<?php echo $this->baseUrl(); ?>/resources/css/modules/admin/images/sample_mini_portfolio2.jpg" style="position: relative;" alt="Thumbnail Preview" />
			</div>
			<br style="clear:both;"/>
			<form name="thumbnail" action="<?php echo $_SERVER["PHP_SELF"];?>" method="post">
				<input type="hidden" name="x1" value="" id="x1" />
				<input type="hidden" name="y1" value="" id="y1" />
				<input type="hidden" name="x2" value="" id="x2" />
				<input type="hidden" name="y2" value="" id="y2" />
				<input type="hidden" name="w" value="" id="w" />
				<input type="hidden" name="h" value="" id="h" />
				<input type="submit" name="upload_thumbnail" value="Save Thumbnail" id="save_thumb" />
			</form>
		</div>
	<hr />
<?php endif;?>
<h2>Charger une image  </h2>
<form name="photo" enctype="multipart/form-data" action="<?=$this->url(array('action'=>'profileimage','controller'=>'profile','module'=>'admin','type'=>'redim'))?>" method="post">

				<span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Ajouter votre photo...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Charger votr photo</span>
                </button>

</form>
