
<script type="text/javascript">  
function treeconstractor(){
	$("#tree").fancytree({
	    source: {
	            url: "<?=$this->url("roles/actions-role-tree")?>"
	    },
	    lazyload: function(e, data){
	 
	            data.result = $.ajax({
	                    url: "<?=$this->url("roles/actions-role-tree")?>",
	                    dataType: "json"
	            });
	    },
	    click: function(event, data) {
            
			console.log(data.node.key+" "+data.node.tooltip);
			 var keydata=data.node.key;
			var keysplit=keydata.split("_");   
			//save in session the key of formation choisie
	    	var url="<?=$this->url("roles")?> ";
                if(keysplit[0]=="Module"){
                    url="<?=$this->url("droits/actions-assigne")?>/"+keysplit[3]+"/"+keysplit[1];
                }else if(keysplit[0]=="Role"){
                    url="<?=$this->url("droits/actions-droit")?>/"+keysplit[1];
                } 

                $.ajax({
                    type:"POST",
                    url: url,
                    data:{
                        niveau:data.node.key
                        ,anneescolaire:1
                    },
                    beforeSend :function(){
                        $('#content_ajax').html("Encours...");
                    },
                    success:function(response){
                        $('#content_ajax').html(response);
                    }
                });
             
    	}
	});

	
	}

$(function(){ 
	treeconstractor(); 
	});  
</script>
<div class="row">
    <div class="col-md-3" id="tree"></div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12"> 
                    <nav class="navbar navbar-expand navbar-orange navbar-dark">
                      <!-- Left navbar links -->
                      <ul class="navbar-nav"> 
                      <a class="nav-link"  href="#" role="button"><i class="fas fa-bars"></i></a>
                        <li class="nav-item d-none d-sm-inline-block">
                          <a href="#" onclick="AjaxOneLoader('<?=$this->url('ressources/actions-ressources')?>','content_ajax')" class="nav-link">Ajouter ressource</a>
                        </li>
                        <li class="nav-item d-none d-sm-inline-block">
                          <a href="#" onclick="AjaxOneLoader('<?=$this->url('roles/actions-role')?>','content_ajax')" class="nav-link">Ajouter role</a>
                        </li>
                      </ul> 
                    </nav> 
            </div>
        </div>
<hr>
        <div class="row">
            <div class="col-md-12"  id="content_ajax"></div>
        </div>

    </div>
</div> 