 


<?php if($this->pageCount): ?>
 
<div>
    <ul class="pagination justify-content-center">
    	<!-- Previous page link -->
    	<?php if(isset($this->previous)): ?>
    	<li class="page-item">
    		<a href="#" onclick="AjaxOneLoader('<?= $this->url($this->route, (isset($this->params) ? $this->params : []), ['query' => ['page' => $this->previous]]); ?>',<?=isset($this->content_id) ?  "'".$this->content_id."'" : 'content_ajax'?>)"
    			tabindex="-1" aria-disabled="true" class="page-link">
    			Précédent
    		</a>
    	</li>
    	<?php else: ?>
    		<li class="page-item disabled">
    			<a href="#" class="page-link">
    				&gt;&gt;
    			</a>
    		</li> <!-- suspect -->
    	<?php endif; ?>
    	<!-- NUmbered page links -->
    	<?php foreach($this->pagesInRange as $page): ?>
    		<?php if($page !== $this->current): ?>
    			<li class="page-item">
    				<a href="#" onclick="AjaxOneLoader('<?= $this->url($this->route,(isset($this->params)? $this->params : []), ['query' => ['page' => $page]]); ?>',<?=isset($this->content_id) ?  "'".$this->content_id."'" : 'content_ajax'?>)" class="page-link"> <?= $page; ?>
    				</a>
    			</li>
    		<?php else: ?>
    			<li class="active page-item">
    				<a href="#" class="page-link">
    					<?= $page; ?>
    				</a>
    			</li>
    		<?php endif; ?>
    	<?php endforeach; ?>
    	<!-- Next page link -->
    	<?php if(isset($this->next)): ?>
    		<li class="page-item">
    			<a href="#" onclick="AjaxOneLoader('<?= $this->url($this->route, (isset($this->params)? $this->params : []), ['query' => ['page' => $this->next]]); ?>',<?=isset($this->content_id) ?  "'".$this->content_id."'" : 'content_ajax'?>)" class="page-link">
				Suivant
    			</a>
    		</li>
    	<?php else: ?>
    		<li class="disabled page-item">
    			<a href="#" class="page-link">
    				&gt;&gt;
    			</a>
    		</li>
    	<?php endif; ?>

    </ul>
</div>
<?php
endif;