<?php

$title =  $this->translate('Authentification'); # page title
# meta keywords
$this->headMeta()->appendName('keywords', 'Login,  Authenticate UVT');
# meta description
$this->headMeta()->appendName('description', 'Login pour inscription');
# page title
$this->headTitle($this->escapeHtml($title));


#form
$form = $this->form;
$form->setAttribute('action', $this->url('loginadmin'));  #oops
$form->prepare();

?>
  
		
	<?= $this->form()->openTag($form); ?> 

	<div class="mb-3">
		<?= $this->formLabel($form->get('email')); ?>
		<div class="form-group">
			<?= $this->formEmail($form->get('email')); ?>
		</div>
		
		<div class="text-danger">
			<?= $this->formElementErrors($form->get('email')); ?>
		</div>
	</div>

	<div class="mb-3">
		<?= $this->formLabel($form->get('password')); ?>
		

		<div class="form-group">
			<?= $this->formPassword($form->get('password')); ?>
		</div>
		
		<div class="text-danger">
			<?= $this->formElementErrors($form->get('password')); ?>
		</div>
	</div>

  
	<!-- check box -->
	<div class="mb-3">
		<div class="custom-control custom-checkbox">
			<?= $this->formCheckbox($form->get('recall')); ?>
			<?= $this->formLabel($form->get('recall')); ?>
		</div>
	</div>

	<!-- submit button -->
	<div class="mb-3 float-right">
		<?= $this->formHidden($form->get('returnUrl')); ?>
		<?= $this->formHidden($form->get('csrf')); ?>
		<div class="text-danger">
			<?= $this->formElementErrors($form->get('csrf')); ?>
		</div>
		<?= $this->formSubmit($form->get('account_login')); ?>
	</div>

	<?= $this->form()->closeTag(); ?>
  