<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthorized Access</title>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/app.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
</head>

<body class="text-center">

    <main role="main" class="container pt-5">
        <h1 class="text-danger pt-2">
            403 - Access Denied
        </h1>

        <p class="text-muted">
            You don't have authorization to access this page</p>
        </p>

        <p>
            <a href="#" onclick="window.history.back(); return false;" class="btn btn-secondary btn-sm">
                Go back to the last page
            </a>
        </p>
    </main>
    
</body>
</html>