<script>  
    $(function(){

        $('[data-toggle="tabajax"]').click(function(e) {
        var $this = $(this),
            loadurl = $this.attr('href'),
            targ = $this.attr('data-target');
            $("#"+targ).html('<div class="overlay dark"><i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">Chargement...</div></div>'); 
          $.get(loadurl, function(data) {
              $("#"+targ).html(data);
          });

        $this.tab('show');
        return false;
      });
      $('[data-toggle="tabajax"]:first').click();

      

    
  });

</script>

<div class="col-md-12">
  <div class="card card-primary card-tabs">
    <div class="card-header p-0 pt-1">
      <ul class="nav nav-tabs" id="custom-tabs-five-tab" role="tablist">
        <li class="nav-item">
          <a   class="nav-link active" data-target="content-tabs" id="custom-tabs-five-overlay-tab" data-toggle="tabajax" href="<?=$this->url('menu/actions-menu-add',['module'=>$this->module_id,'id'=>$this->menu_id])?>" role="tab" aria-controls="custom-tabs-five-overlay" aria-selected="true">Modifier Menu</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-target="content-tabs" id="custom-tabs-five-overlay-dark-tab" data-toggle="tabajax" href="<?=$this->url('menu/actions-menu-add-sub',['module'=>$this->module_id,'idsubmenu'=>$this->menu_id])?>" role="tab" aria-controls="custom-tabs-five-overlay-dark" aria-selected="false">Ajouter un sous-menu</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-target="content-tabs" id="custom-tabs-five-normal-tab" data-toggle="tabajax" href="<?=$this->url('menu/actions-menu-lister',['module'=>$this->module_id,'idsubmenu'=>$this->menu_id])?>" role="tab" aria-controls="custom-tabs-five-normal" aria-selected="false">Liste des sous menu</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content" id="content-tabs">
         
      </div>
    </div>
    <!-- /.card -->
  </div>
</div> 