<p dir="RTL" align="left">
    <em>السنة الجامعية:</em>
    <em>:................/...........</em>
    <em>.....</em>
    <em>.</em>
    <em></em>
</p>
<p dir="RTL" align="left">
    <em>المستوى الدراسي: السنة</em>
    <em>........</em>
    <em> السداسي:</em>
    <em>…......</em>
    <em></em>
</p>
<p dir="RTL" align="center">
    <strong>مطلب ترشح للقيام بساعات تدريس غير حضورية في إطار</strong>
    <strong>شهادة</strong>
    <em>
        .......................................................................................................................................................
    </em>
    <em></em>
</p>
<p dir="RTL">
    اسم ولقب المدرس :
    <strong>
        <em>
            ....................................................................................................................................................
        </em>
    </strong>
    <strong><em></em></strong>
</p>
<p dir="RTL">
    تاريخ و مكان الولادة :
    <strong>
        <em>
            ......................................................................................................................................................
        </em>
    </strong>
</p>
<div align="right">
    <table dir="rtl" cellspacing="0" cellpadding="0" border="1" align="right">
        <tbody>
        <tr>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
        </tr>
        </tbody>
    </table>
</div>
<p dir="RTL" align="left">
    رقم بطا قة التعريف: :المسلمة في:	<strong><em>...............................................</em></strong>
</p>
<div align="right">
    <table dir="rtl" cellspacing="0" cellpadding="0" border="1" align="right">
        <tbody>
        <tr>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
            <td width="21" valign="top">
            </td>
        </tr>
        </tbody>
    </table>
</div>
<p dir="RTL">
    المعرف الوحيد :
</p>
<p dir="RTL" align="left">
    الهاتف القار:
    <strong>
        <em>
            ................................................................
        </em>
    </strong>
    المحمول:
    <strong>
        <em>
            ...............................................................................
        </em>
    </strong>
</p>
<p dir="RTL">
    العنوان الإلكتروني:
    <strong>
        <em>
            ......................................................................
        </em>
    </strong>
    <strong><em>@</em></strong>
    <strong>
        <em>
            .............................................................................
        </em>
    </strong>
</p>
<p dir="RTL">
    الوظيفة الأساسية:
    <strong>
        <em>
            ....................................................................
        </em>
    </strong>
    الرتبة :
    <strong>
        <em>
            .......................................................................
        </em>
    </strong>
</p>
<p dir="RTL">
    المؤسسة الأصلية :
    <strong>
        <em>
            ...............................................................................................................................................
        </em>
    </strong>
</p>
<div align="right">
    <table dir="rtl" cellspacing="0" cellpadding="0" border="1" align="right">
        <tbody>
        <tr>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
            <td width="25" valign="top">
            </td>
        </tr>
        </tbody>
    </table>
</div>
<p dir="RTL" align="left">
    رقم الحساب الجاري :<strong>(اجباري)</strong>
    <br clear="all"/>
    أعلى شهادة علمية :
    <strong>
        <em>
            ........................................................................................................................................................
        </em>
    </strong>
</p>
<p dir="RTL">
    الاختصاص :
    <strong>
        <em>
            ......................................................................................................................................................................
        </em>
    </strong>
</p>
<p dir="RTL">
    مادة التدريس :
    <strong>
        <em>
            ..........................................................................................................................
            ........................................
        </em>
    </strong>
</p>
<div align="right">
    <table dir="rtl" cellspacing="0" cellpadding="0" border="1">
        <tbody>
        <tr>
            <td width="170" valign="top">
                <p dir="RTL" align="left">
                    <strong><em>نوع ساعات التدريس</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="180" valign="top">
                <p dir="RTL" align="left">
                    <strong><em>عدد الساعات</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="left">
                    <strong><em>عدد الطلبة</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="left">
                    <strong><em>الجملة</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
        </tr>
        <tr>
            <td width="170" valign="top">
                <p dir="RTL" align="left">
                    <strong><em>تبادل الرسائل الإلكترونية</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="180" valign="top">
                <p dir="RTL" align="left">
                    <strong>
                        <em>
                            ساعتان (02) أشغال مسيرة للطالب الواحد في
                            السداسي
                        </em>
                    </strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em> </em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em> </em></strong>
                </p>
            </td>
        </tr>
        <tr>
            <td width="170" valign="top">
                <p dir="LTR" align="right">
                    <strong><em>التحاور الإلكتروني:</em></strong>
                    <strong><em></em></strong>
                </p>
                <p dir="RTL" align="left">
                    <strong><em>(Chat)</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="180" valign="top">
                <p dir="RTL" align="left">
                    <strong>
                        <em>ساعة واحدة(01) أشغال مسيرة في السداسي</em>
                    </strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em> </em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em>01</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
        </tr>
        <tr>
            <td width="170">
                <p dir="RTL" align="left">
                    <strong><em>حصص الحوار والتنشيط:</em></strong>
                    <strong><em></em></strong>
                </p>
                <p dir="RTL" align="center">
                    <strong><em>(Forum)</em></strong>
                </p>
            </td>
            <td width="180">
                <p dir="RTL" align="left">
                    <strong>
                        <em>
                            ساعتان أشغال(02) مسيرة للطالب الواحد في السداسي
                        </em>
                    </strong>
                    <em></em>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em> </em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em> </em></strong>
                </p>
            </td>
        </tr>
        <tr>
            <td width="170">
                <p dir="RTL" align="left">
                    <strong><em>التجمع الحضوري:</em></strong>
                    <strong><em></em></strong>
                </p>
                <p dir="RTL" align="left">
                    <strong><em>(Regroupement présentiel )</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
            <td width="180">
                <p dir="RTL" align="left">
                    <strong>
                        <em>سبع ساعات (07) أشغال مسيّرة في السداسي</em>
                    </strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em> </em></strong>
                </p>
            </td>
            <td width="104" valign="top">
                <p dir="RTL" align="center">
                    <strong><em>07</em></strong>
                    <strong><em></em></strong>
                </p>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<table cellspacing="0" cellpadding="0">
    <tbody>
    <tr>
        <td width="273" height="40">
            <table width="100%" cellspacing="0" cellpadding="0">
                <tbody>
                <tr>
                    <td>
                        <div>
                            <p>
                                <strong>
                                    <em>إمضاء المشرف على الشهادة </em>
                                </strong>
                                <strong><em></em></strong>
                            </p>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<p>
    تونس في : ...............................
</p>
<strong><em> </em></strong>
<table cellspacing="0" cellpadding="0">
    <tbody>
    <tr>
        <td width="169" height="34">
            <table width="100%" cellspacing="0" cellpadding="0">
                <tbody>
                <tr>
                    <td>
                        <div>
                            <p>
                                <strong><em>إمضاء المدرس</em></strong>
                                <strong><em></em></strong>
                            </p>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<table cellspacing="0" cellpadding="0">
    <tbody>
    <tr>
        <td width="301" height="46">
            <table width="100%" cellspacing="0" cellpadding="0">
                <tbody>
                <tr>
                    <td>
                        <div>
                            <p align="left">
                                <strong>
                                    <em>
                                        إمضاء رئيس جامعة تونس
                                        الإفتراضية
                                    </em>
                                </strong>
                                <strong><em> </em></strong>
                                <strong><em></em></strong>
                            </p>
                            <p>
                                <strong><em> </em></strong>
                            </p>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<strong><em></em></strong>
<p dir="RTL">
    <strong><em> </em></strong>
</p>
<p dir="RTL">
    <strong><em> </em></strong>
</p>
<br clear="ALL"/>
<p dir="RTL">
    <strong>
        <em>
            <br/>
            <br/>
            <br/>
        </em>
    </strong>
</p>
<p dir="RTL">
    <strong>ملاحظة</strong>
    : - يجب أن يرفق هذا المطلب بنسخة من ب.ت.و. وشهادة عمل أو آخر قرار تسمية في
    الرتبة (في صورة انتماء المترشح إلى سلك الوظيفة العمومية) وترخيص من المؤسسة
    الأصلية و كشف الهوية البنكية ونسخة من آخرشهادة علمية (لغير المدرّسين
    الجامعيين).
</p>
